# Generated by Django 4.2.7 on 2023-11-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(choices=[('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior')], default='JR', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_offered', models.DateField(editable=False)),
                ('salary', models.IntegerField()),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='employees_e_first_n_597cbd_idx'), models.Index(fields=['last_name', 'salary'], name='employees_e_last_na_60efe3_idx'), models.Index(fields=['last_name', 'job_title'], name='employees_e_last_na_b05497_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('salary__gte', 50000)), name='salary_gte_50000_RUB'),
        ),
    ]
