# Generated by Django 4.2.7 on 2023-11-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_date_offered_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='salary_gte_50000_RUB',
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('salary__gte', 50000)), name='salary_gte_50000_RUB', violation_error_message='It is impossible to set a salary below the subsistence level.'),
        ),
    ]
