# Generated by Django 4.2.8 on 2023-12-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('IN', 'Intern'), ('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('CEO', 'CEO')], default='IN', max_length=100),
        ),
    ]
